insert into post values(1, 'Blog Post', 'this is a blog post ', 'akshay', 44);
insert into post values(2, 'Macbooks', 'Macbooks are great ', 'apple employee', 9);
insert into post values(3, 'House', 'this is a great house ', 'deepanshu', 4);
insert into post values(4, 'Food', 'Food is always good ', 'kartikey', 15);
insert into post values(5, 'Work', 'I like working ', 'Anne', 1);
insert into comment values(1, 'Hello There');
insert into comment values(2, 'Love it');
insert into comment values(3, 'Nice post');
insert into comment values(5, 'I hate this');
insert into comment values(4, 'I dont agree');
insert into comment values(4, 'You write well');
